In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import precision_recall_curve
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn import tree
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB

In [2]:
df = pd.read_csv("Predicting_Depression.csv")

In [3]:
df

,Timestamp,Age,Gender,Profession,Which Social media do you frequently used?,How much time do you spend in Social media?,What is your main purpose to use social media?,Do you reveal about your mental breakdown through social media posts?,"If yes, then what is the reason behind it?",Are you connected with any mental health support forum?,Unnamed: 10,Unnamed: 11,Result
0,3/3/2022 23:02:42,19 - 25,Female,Student,Instagram,Often,To get Pleasure or motivation,Yes,I don't have supportive family member.,Yes,NaN,NaN,1
1,3/3/2022 23:14:25,12 - 18,Female,Student,Facebook,Often,To get Pleasure or motivation,No,NaN,No,NaN,NaN,0
2,3/3/2022 23:15:36,19 - 25,Female,Student,Facebook,Frequently,To stay connected with people,No,NaN,No,NaN,NaN,0
3,3/3/2022 23:15:43,25 - 40,Male,Service Holder,Facebook,Frequently,To stay connected with people,No,NaN,No,NaN,NaN,0
4,3/3/2022 23:16:03,25 - 40,Male,Service Holder,Twitter,Often,To get Pleasure or motivation,Yes,I don't have supportive family member.,Yes,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
300,3/4/2022 18:17:44,25 - 40,Male,Businessman,Facebook,Rarely,To stay connected with people,No,NaN,No,NaN,NaN,0
301,3/4/2022 18:17:48,25 - 40,Female,Businessman,Twitter,Often,To get Pleasure or motivation,Yes,I don't have supportive family member.,Yes,NaN,NaN,1
302,3/4/2022 18:18:01,12 - 18,Female,Businessman,Twitter,Rarely,To stay connected with people,No,NaN,Yes,NaN,NaN,0
303,3/4/2022 18:56:38,19 - 25,Female,Student,Facebook,Often,To get Pleasure or motivation,Yes,"I haven't so many real friend, with whom I can...",No,NaN,NaN,1
304,3/4/2022 19:40:57,19 - 25,Female,Student,Facebook,Often,To get Pleasure or motivation,No,NaN,No,NaN,NaN,0

In [4]:
df.drop(["Timestamp","Unnamed: 10","Unnamed: 11"],axis=1,inplace=True)

In [5]:
df

,Age,Gender,Profession,Which Social media do you frequently used?,How much time do you spend in Social media?,What is your main purpose to use social media?,Do you reveal about your mental breakdown through social media posts?,"If yes, then what is the reason behind it?",Are you connected with any mental health support forum?,Result
0,19 - 25,Female,Student,Instagram,Often,To get Pleasure or motivation,Yes,I don't have supportive family member.,Yes,1
1,12 - 18,Female,Student,Facebook,Often,To get Pleasure or motivation,No,NaN,No,0
2,19 - 25,Female,Student,Facebook,Frequently,To stay connected with people,No,NaN,No,0
3,25 - 40,Male,Service Holder,Facebook,Frequently,To stay connected with people,No,NaN,No,0
4,25 - 40,Male,Service Holder,Twitter,Often,To get Pleasure or motivation,Yes,I don't have supportive family member.,Yes,1
...,...,...,...,...,...,...,...,...,...,...
300,25 - 40,Male,Businessman,Facebook,Rarely,To stay connected with people,No,NaN,No,0
301,25 - 40,Female,Businessman,Twitter,Often,To get Pleasure or motivation,Yes,I don't have supportive family member.,Yes,1
302,12 - 18,Female,Businessman,Twitter,Rarely,To stay connected with people,No,NaN,Yes,0
303,19 - 25,Female,Student,Facebook,Often,To get Pleasure or motivation,Yes,"I haven't so many real friend, with whom I can...",No,1
304,19 - 25,Female,Student,Facebook,Often,To get Pleasure or motivation,No,NaN,No,0

In [6]:
df.drop(["Profession","Which Social media do you frequently used?"],axis=1,inplace=True)

In [7]:
df.rename(columns={"How much time do you spend in Social media?":"spent_Time","What is your main purpose to use social media?":
                   "purpose_Of_use","Do you reveal about your mental breakdown through social media posts?":
                   "Reveal_mental_breakdown","If yes, then what is the reason behind it?":"reason_behind_usingSocialMedia",
                   "Are you connected with any mental health support forum?":"Connected_with_MentalHealth_forum"
                  },inplace=True)
df

,Age,Gender,spent_Time,purpose_Of_use,Reveal_mental_breakdown,reason_behind_usingSocialMedia,Connected_with_MentalHealth_forum,Result
0,19 - 25,Female,Often,To get Pleasure or motivation,Yes,I don't have supportive family member.,Yes,1
1,12 - 18,Female,Often,To get Pleasure or motivation,No,NaN,No,0
2,19 - 25,Female,Frequently,To stay connected with people,No,NaN,No,0
3,25 - 40,Male,Frequently,To stay connected with people,No,NaN,No,0
4,25 - 40,Male,Often,To get Pleasure or motivation,Yes,I don't have supportive family member.,Yes,1
...,...,...,...,...,...,...,...,...
300,25 - 40,Male,Rarely,To stay connected with people,No,NaN,No,0
301,25 - 40,Female,Often,To get Pleasure or motivation,Yes,I don't have supportive family member.,Yes,1
302,12 - 18,Female,Rarely,To stay connected with people,No,NaN,Yes,0
303,19 - 25,Female,Often,To get Pleasure or motivation,Yes,"I haven't so many real friend, with whom I can...",No,1
304,19 - 25,Female,Often,To get Pleasure or motivation,No,NaN,No,0

In [8]:
spentTime = pd.get_dummies(df.spent_Time)

In [9]:
concatDf = pd.concat([df,spentTime],axis="columns")
concatDf

,Age,Gender,spent_Time,purpose_Of_use,Reveal_mental_breakdown,reason_behind_usingSocialMedia,Connected_with_MentalHealth_forum,Result,Almost Never,Frequently,Often,Rarely
0,19 - 25,Female,Often,To get Pleasure or motivation,Yes,I don't have supportive family member.,Yes,1,0,0,1,0
1,12 - 18,Female,Often,To get Pleasure or motivation,No,NaN,No,0,0,0,1,0
2,19 - 25,Female,Frequently,To stay connected with people,No,NaN,No,0,0,1,0,0
3,25 - 40,Male,Frequently,To stay connected with people,No,NaN,No,0,0,1,0,0
4,25 - 40,Male,Often,To get Pleasure or motivation,Yes,I don't have supportive family member.,Yes,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
300,25 - 40,Male,Rarely,To stay connected with people,No,NaN,No,0,0,0,0,1
301,25 - 40,Female,Often,To get Pleasure or motivation,Yes,I don't have supportive family member.,Yes,1,0,0,1,0
302,12 - 18,Female,Rarely,To stay connected with people,No,NaN,Yes,0,0,0,0,1
303,19 - 25,Female,Often,To get Pleasure or motivation,Yes,"I haven't so many real friend, with whom I can...",No,1,0,0,1,0
304,19 - 25,Female,Often,To get Pleasure or motivation,No,NaN,No,0,0,0,1,0

In [10]:
le = LabelEncoder()
dfle = concatDf 
dfle.Gender = le.fit_transform(dfle.Gender)
dfle.purpose_Of_use = le.fit_transform(dfle.purpose_Of_use)
dfle.Reveal_mental_breakdown = le.fit_transform(dfle.Reveal_mental_breakdown)
dfle.Connected_with_MentalHealth_forum = le.fit_transform(dfle.Connected_with_MentalHealth_forum)
dfle

,Age,Gender,spent_Time,purpose_Of_use,Reveal_mental_breakdown,reason_behind_usingSocialMedia,Connected_with_MentalHealth_forum,Result,Almost Never,Frequently,Often,Rarely
0,19 - 25,0,Often,0,1,I don't have supportive family member.,1,1,0,0,1,0
1,12 - 18,0,Often,0,0,NaN,0,0,0,0,1,0
2,19 - 25,0,Frequently,1,0,NaN,0,0,0,1,0,0
3,25 - 40,1,Frequently,1,0,NaN,0,0,0,1,0,0
4,25 - 40,1,Often,0,1,I don't have supportive family member.,1,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
300,25 - 40,1,Rarely,1,0,NaN,0,0,0,0,0,1
301,25 - 40,0,Often,0,1,I don't have supportive family member.,1,1,0,0,1,0
302,12 - 18,0,Rarely,1,0,NaN,1,0,0,0,0,1
303,19 - 25,0,Often,0,1,"I haven't so many real friend, with whom I can...",0,1,0,0,1,0
304,19 - 25,0,Often,0,0,NaN,0,0,0,0,1,0

In [11]:
dfle.drop(["Age","spent_Time"],axis=1,inplace=True)
dfle

,Gender,purpose_Of_use,Reveal_mental_breakdown,reason_behind_usingSocialMedia,Connected_with_MentalHealth_forum,Result,Almost Never,Frequently,Often,Rarely
0,0,0,1,I don't have supportive family member.,1,1,0,0,1,0
1,0,0,0,NaN,0,0,0,0,1,0
2,0,1,0,NaN,0,0,0,1,0,0
3,1,1,0,NaN,0,0,0,1,0,0
4,1,0,1,I don't have supportive family member.,1,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...
300,1,1,0,NaN,0,0,0,0,0,1
301,0,0,1,I don't have supportive family member.,1,1,0,0,1,0
302,0,1,0,NaN,1,0,0,0,0,1
303,0,0,1,"I haven't so many real friend, with whom I can...",0,1,0,0,1,0
304,0,0,0,NaN,0,0,0,0,1,0

In [12]:
reason = pd.get_dummies(df.reason_behind_usingSocialMedia)
reason

,I don't have supportive family member.,"I haven't so many real friend, with whom I can share.",Its easier for me to use this platform for revealing any kind of breakdown and it reaches to people quickly,Social media is more comfortable for me.,it seems hard to share with someone real
0,1,0,0,0,0
1,0,0,0,0,0
2,0,0,0,0,0
3,0,0,0,0,0
4,1,0,0,0,0
...,...,...,...,...,...
300,0,0,0,0,0
301,1,0,0,0,0
302,0,0,0,0,0
303,0,1,0,0,0
304,0,0,0,0,0

In [13]:
finalDf = pd.concat([dfle,reason],axis="columns")
finalDf

,Gender,purpose_Of_use,Reveal_mental_breakdown,reason_behind_usingSocialMedia,Connected_with_MentalHealth_forum,Result,Almost Never,Frequently,Often,Rarely,I don't have supportive family member.,"I haven't so many real friend, with whom I can share.",Its easier for me to use this platform for revealing any kind of breakdown and it reaches to people quickly,Social media is more comfortable for me.,it seems hard to share with someone real
0,0,0,1,I don't have supportive family member.,1,1,0,0,1,0,1,0,0,0,0
1,0,0,0,NaN,0,0,0,0,1,0,0,0,0,0,0
2,0,1,0,NaN,0,0,0,1,0,0,0,0,0,0,0
3,1,1,0,NaN,0,0,0,1,0,0,0,0,0,0,0
4,1,0,1,I don't have supportive family member.,1,1,0,0,1,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300,1,1,0,NaN,0,0,0,0,0,1,0,0,0,0,0
301,0,0,1,I don't have supportive family member.,1,1,0,0,1,0,1,0,0,0,0
302,0,1,0,NaN,1,0,0,0,0,1,0,0,0,0,0
303,0,0,1,"I haven't so many real friend, with whom I can...",0,1,0,0,1,0,0,1,0,0,0
304,0,0,0,NaN,0,0,0,0,1,0,0,0,0,0,0

In [14]:
finalDf.drop(finalDf.columns[[3,12,13,14]],axis=1,inplace=True)
finalDf

,Gender,purpose_Of_use,Reveal_mental_breakdown,Connected_with_MentalHealth_forum,Result,Almost Never,Frequently,Often,Rarely,I don't have supportive family member.,"I haven't so many real friend, with whom I can share."
0,0,0,1,1,1,0,0,1,0,1,0
1,0,0,0,0,0,0,0,1,0,0,0
2,0,1,0,0,0,0,1,0,0,0,0
3,1,1,0,0,0,0,1,0,0,0,0
4,1,0,1,1,1,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
300,1,1,0,0,0,0,0,0,1,0,0
301,0,0,1,1,1,0,0,1,0,1,0
302,0,1,0,1,0,0,0,0,1,0,0
303,0,0,1,0,1,0,0,1,0,0,1
304,0,0,0,0,0,0,0,1,0,0,0

In [15]:
finalDf.rename(columns={"I don't have supportive family member.":"No_supportive_familyMember",
                        "I haven't so many real friend, with whom I can share.":"Less_real_Friend"    
},inplace=True)
finalDf

,Gender,purpose_Of_use,Reveal_mental_breakdown,Connected_with_MentalHealth_forum,Result,Almost Never,Frequently,Often,Rarely,No_supportive_familyMember,Less_real_Friend
0,0,0,1,1,1,0,0,1,0,1,0
1,0,0,0,0,0,0,0,1,0,0,0
2,0,1,0,0,0,0,1,0,0,0,0
3,1,1,0,0,0,0,1,0,0,0,0
4,1,0,1,1,1,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
300,1,1,0,0,0,0,0,0,1,0,0
301,0,0,1,1,1,0,0,1,0,1,0
302,0,1,0,1,0,0,0,0,1,0,0
303,0,0,1,0,1,0,0,1,0,0,1
304,0,0,0,0,0,0,0,1,0,0,0

In [16]:
X = finalDf[['Gender','purpose_Of_use','Reveal_mental_breakdown','Connected_with_MentalHealth_forum','Almost Never','Frequently',
            'Often','Rarely','No_supportive_familyMember','Less_real_Friend']]
y = finalDf['Result']
X

,Gender,purpose_Of_use,Reveal_mental_breakdown,Connected_with_MentalHealth_forum,Almost Never,Frequently,Often,Rarely,No_supportive_familyMember,Less_real_Friend
0,0,0,1,1,0,0,1,0,1,0
1,0,0,0,0,0,0,1,0,0,0
2,0,1,0,0,0,1,0,0,0,0
3,1,1,0,0,0,1,0,0,0,0
4,1,0,1,1,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...
300,1,1,0,0,0,0,0,1,0,0
301,0,0,1,1,0,0,1,0,1,0
302,0,1,0,1,0,0,0,1,0,0
303,0,0,1,0,0,0,1,0,0,1
304,0,0,0,0,0,0,1,0,0,0

In [69]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2)

In [70]:
LRmodel = LogisticRegression()
LRmodel.fit(X_train, y_train)

LogisticRegression()

In [71]:
y_predicted = LRmodel.predict(X_test)
y_predicted

array([0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0], dtype=int64)

In [72]:
LRmodel.score(X_test,y_test)

0.9836065573770492

In [73]:
confusion_matrix(y_test,y_predicted)

array([[29,  1],
       [ 0, 31]], dtype=int64)

In [75]:
precision, recall, thresolds = precision_recall_curve(y_test,y_predicted)
precision

array([0.96875, 1.     ])

In [76]:
recall

array([1., 0.])

In [120]:
from sklearn.metrics import f1_score
f1_score(y_test,y_predicted)

0.9906542056074767

In [77]:

thresolds

array([1], dtype=int64)

In [123]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2)

In [124]:
svmModel = SVC()
svmModel.fit(X_train,y_train)

SVC()

In [125]:
y_predicted = svmModel.predict(X_test)
y_predicted

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1], dtype=int64)

In [126]:
svmModel.score(X_test,y_test)

0.9836065573770492

In [127]:
confusion_matrix(y_test,y_predicted)

array([[29,  1],
       [ 0, 31]], dtype=int64)

In [128]:
precision, recall, thresolds = precision_recall_curve(y_test,y_predicted)
precision

array([0.96875, 1.     ])

In [129]:
recall

array([1., 0.])

In [130]:
from sklearn.metrics import f1_score
f1_score(y_test,y_predicted)

0.9841269841269841

In [131]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2)

In [132]:
dtModel = tree.DecisionTreeClassifier()
dtModel.fit(X_train,y_train)
y_predicted = dtModel.predict(X_test)
y_predicted

array([1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0], dtype=int64)

In [133]:
dtModel.score(X_test,y_test)

0.9672131147540983

In [134]:
confusion_matrix(y_test,y_predicted)

array([[27,  0],
       [ 2, 32]], dtype=int64)

In [135]:
precision, recall, thresolds = precision_recall_curve(y_test,y_predicted)

In [136]:
precision

array([0.55737705, 1.        , 1.        ])

In [137]:
recall

array([1.        , 0.94117647, 0.        ])

In [138]:
thresolds

array([0, 1], dtype=int64)

In [139]:
from sklearn.metrics import f1_score
f1_score(y_test,y_predicted)

0.9696969696969697

In [140]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2)

In [141]:
knModel = KNeighborsClassifier(n_neighbors=3)
knModel.fit(X_train,y_train)
y_predicted = knModel.predict(X_test)
y_predicted

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1], dtype=int64)

In [142]:
knModel.score(X_test,y_test)

0.9508196721311475

In [143]:
confusion_matrix(y_test,y_predicted)

array([[25,  3],
       [ 0, 33]], dtype=int64)

In [144]:
precision, recall, thresolds = precision_recall_curve(y_test,y_predicted)

In [145]:
precision

array([0.91666667, 1.        ])

In [146]:
recall

array([1., 0.])

In [147]:
thresolds

array([1], dtype=int64)

In [148]:
from sklearn.metrics import f1_score
f1_score(y_test,y_predicted)

0.9565217391304348

In [152]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2)

In [111]:
rfModel = RandomForestClassifier()
rfModel.fit(X_train,y_train)
y_predicted = rfModel.predict(X_test)
y_predicted

array([0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1], dtype=int64)

In [112]:
rfModel.score(X_test,y_test)

1.0

In [116]:
confusion_matrix(y_test,y_predicted)

array([[38,  1],
       [ 0, 53]], dtype=int64)

In [118]:
precision, recall, thresolds = precision_recall_curve(y_test,y_predicted)

In [84]:
precision

array([0.96875, 1.     ])

In [58]:
recall

array([1.        , 0.96428571, 0.        ])

In [59]:
thresolds

array([0, 1], dtype=int64)

In [153]:
from sklearn.metrics import f1_score
f1_score(y_test,y_predicted)

0.5714285714285715

In [154]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2)

In [155]:
Nbmodel = GaussianNB()
Nbmodel.fit(X_train,y_train)
y_predicted = Nbmodel.predict(X_test)
y_predicted

array([1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1], dtype=int64)

In [156]:
Nbmodel.score(X_test,y_test)

0.9836065573770492

In [157]:
confusion_matrix(y_test,y_predicted)

array([[24,  1],
       [ 0, 36]], dtype=int64)

In [158]:
precision, recall, thresolds = precision_recall_curve(y_test,y_predicted)

In [159]:
precision

array([0.97297297, 1.        ])

In [160]:
recall

array([1., 0.])

In [68]:
thresolds

array([1], dtype=int64)

In [161]:
from sklearn.metrics import f1_score
f1_score(y_test,y_predicted)

0.9863013698630138